import matplotlib.pyplot as plt

with open('data.txt', 'r') as file:
    content = file.readlines()
    x = list(content[0])
    v = list(content[1])
    a = list(content[2])
    t = list(content[3])

plt.figure("Harmonic oscilator")
fig = plt.subplot()
plt.subplot(2,2,1)
plt.plot(t,x)
plt.xlabel("t [s]")
plt.ylabel("x [m]")
plt.title("x-t graf")
plt.subplot(2,2,2)
plt.plot(t,v)
plt.xlabel("t [s]")
plt.ylabel("v [m/s]")
plt.title("v-t graf")
plt.subplot(2,2,3)
plt.plot(t,a)
plt.xlabel("t [s]")
plt.ylabel("a [m/s^2]")
plt.title("a-t graf")
plt.subplots_adjust(wspace = 0.4, hspace = 0.6)
plt.show()